import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import Providers from "./providers";
import { AuthProvider } from "./lib/useAuth";

// 樣式引入
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Theme>
          <Providers>
            <AuthProvider>{children}</AuthProvider>
          </Providers>
        </Theme>
      </body>
    </html>
  );
}
